export const ADDTRANSACTION = "ADDTRANSACTION";
export const CHANGE_SETTINGS = "CHANGE_SETTINGS";
export const TRANSACTIONERROR = "TRANSACTIONERROR";
export const TRANSACTIONMESSAGE = "TRANSACTIONMESSAGE";